'use strict';
/* ============================================================
   МОСТ МЕЖДУ ПРОЦЕССАМИ
   ============================================================
   Окно с интерфейсом не имеет доступа ни к файлам, ни к базе, ни к
   сети — только к перечисленным здесь вызовам. Это не формальность:
   в приложении будет показ веб-содержимого и работа с ключом от
   модели, и прямой доступ из окна к файловой системе означал бы, что
   любая ошибка в разметке становится дырой.
   ============================================================ */
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  overview: () => ipcRenderer.invoke('overview'),
  expenses: (q) => ipcRenderer.invoke('expenses', q),
  capital: () => ipcRenderer.invoke('capital'),
  forecast: () => ipcRenderer.invoke('forecast'),
  loanPlan: (extra) => ipcRenderer.invoke('loan-plan', extra),
  plans: () => ipcRenderer.invoke('plans'),
  planTag: (id, axis, value) => ipcRenderer.invoke('plan-tag', id, axis, value),
  calendar: (q) => ipcRenderer.invoke('calendar', q),
  dayNote: (date, text) => ipcRenderer.invoke('day-note', date, text),
  payments: () => ipcRenderer.invoke('payments'),
  resolveQuestion: (key) => ipcRenderer.invoke('question-done', key),
  skipPayment: (id) => ipcRenderer.invoke('payment-skip', id),
  addQuestion: (q) => ipcRenderer.invoke('question-add', q),
  setQuiet: (date, on) => ipcRenderer.invoke('day-quiet', date, on),
  setAside: (id, amount) => ipcRenderer.invoke('plan-aside', id, amount),
  exportPeriod: (dir, from, to) => ipcRenderer.invoke('export-period', dir, from, to),
  formData: () => ipcRenderer.invoke('form-data'),
  reconCalc: (date) => ipcRenderer.invoke('recon-calc', date),
  loanPreview: (q) => ipcRenderer.invoke('loan-preview', q),
  addOperation: (op) => ipcRenderer.invoke('add-operation', op),
  addCategory: (c) => ipcRenderer.invoke('add-category', c),
  savePlan: (p) => ipcRenderer.invoke('save-plan', p),
  saveRecurring: (r) => ipcRenderer.invoke('save-recurring', r),
  saveGoal: (g) => ipcRenderer.invoke('save-goal', g),
  saveAccount: (a) => ipcRenderer.invoke('save-account', a),
  saveLoan: (l) => ipcRenderer.invoke('save-loan', l),
  saveRecon: (r) => ipcRenderer.invoke('save-recon', r),
  dropPlan: (id) => ipcRenderer.invoke('drop-plan', id),
  pauseRecurring: (id) => ipcRenderer.invoke('pause-recurring', id),
  undo: (token) => ipcRenderer.invoke('undo', token),
  settings: () => ipcRenderer.invoke('settings'),
  prefs: () => ipcRenderer.invoke('prefs'),
  setPref: (key, value) => ipcRenderer.invoke('pref-set', key, value),
  editAccount: (a) => ipcRenderer.invoke('account-edit', a),
  reorderAccounts: (ids) => ipcRenderer.invoke('account-reorder', ids),
  archiveAccount: (id) => ipcRenderer.invoke('account-archive', id),
  restoreAccount: (id) => ipcRenderer.invoke('account-restore', id),
  editCategory: (c) => ipcRenderer.invoke('category-edit', c),
  mergeCategory: (from, to) => ipcRenderer.invoke('category-merge', from, to),
  archiveCategory: (name) => ipcRenderer.invoke('category-archive', name),
  restoreCategory: (name) => ipcRenderer.invoke('category-restore', name),
  deleteCategory: (name) => ipcRenderer.invoke('category-delete', name),
  resumeRecurring: (id) => ipcRenderer.invoke('recurring-resume', id),
  setLoanRate: (rate) => ipcRenderer.invoke('loan-rate', rate),
  setCardTerms: (t) => ipcRenderer.invoke('card-terms', t),
  setAiKey: (key) => ipcRenderer.invoke('ai-key-set', key),
  clearAiKey: () => ipcRenderer.invoke('ai-key-clear'),
  checkAiKey: () => ipcRenderer.invoke('ai-key-check'),
  aiModels: () => ipcRenderer.invoke('ai-models'),
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  pickFile: () => ipcRenderer.invoke('pick-file'),
  reveal: (which) => ipcRenderer.invoke('reveal', which),
  moveData: (dir) => ipcRenderer.invoke('data-move', dir),
  backupNow: () => ipcRenderer.invoke('backup-now'),
  exportCsv: (dir, tables) => ipcRenderer.invoke('export-csv', dir, tables),
  importPreview: (file) => ipcRenderer.invoke('import-preview', file),
  importApply: (token, withDups) => ipcRenderer.invoke('import-apply', token, withDups),
  integrity: () => ipcRenderer.invoke('integrity'),
  changelog: () => ipcRenderer.invoke('changelog'),
  assistantMeta: () => ipcRenderer.invoke('assistant-meta'),
  assistantAsk: (q) => ipcRenderer.invoke('assistant-ask', q),
  assistantStop: () => ipcRenderer.invoke('assistant-stop'),
  assistantReset: () => ipcRenderer.invoke('assistant-reset'),
  assistantSave: (cards) => ipcRenderer.invoke('assistant-save', cards),
  onAssistantStep: (cb) => { ipcRenderer.on('assistant-step', (e, s) => cb(s)); },
  onboardState: () => ipcRenderer.invoke('onboard-state'),
  onboardApply: (p) => ipcRenderer.invoke('onboard-apply', p),
  comments: () => ipcRenderer.invoke('comments'),
  commentsRefresh: (screen) => ipcRenderer.invoke('comments-refresh', screen),
  onComments: (cb) => { ipcRenderer.on('comments', (e, s) => cb(s)); },
  fxStatus: () => ipcRenderer.invoke('fx-status'),
  fxRefresh: () => ipcRenderer.invoke('fx-refresh'),
  fxManual: (cur, raw) => ipcRenderer.invoke('fx-manual', cur, raw),
  fxEnsure: (cur) => ipcRenderer.invoke('fx-ensure', cur),
  onFx: (cb) => { ipcRenderer.on('fx', (e, s) => cb(s)); },
  /* Окно показано: мастер начинает приветствие, когда его уже видно. */
  onShown: (cb) => { ipcRenderer.on('win-shown', () => cb()); },
  reports: () => ipcRenderer.invoke('reports'),
  reportsRead: (periods) => ipcRenderer.invoke('reports-read', periods),
  onReport: (cb) => { ipcRenderer.on('report', (e, s) => cb(s)); },
  appInfo: () => ipcRenderer.invoke('app-info'),
  /* Обновления: адрес страницы и команда установки — у главного процесса,
     окно передаёт только «что сделать». */
  updateState: () => ipcRenderer.invoke('update-state'),
  updateCheck: () => ipcRenderer.invoke('update-check'),
  updateLater: () => ipcRenderer.invoke('update-later'),
  updateInstall: () => ipcRenderer.invoke('update-install'),
  updateCopy: () => ipcRenderer.invoke('update-copy'),
  updatePage: () => ipcRenderer.invoke('update-page'),
  onUpdate: (cb) => { ipcRenderer.on('update', (e, s) => cb(s)); },
});
